version: 2
jobs:
    build:
        working_directory: ~/generator-angular-bro
        docker:
            - image: circleci/node:6.11.0
        steps:
            - checkout
            - run:
                name: update-npm
                command: 'sudo npm install -g npm@^4'
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: install-npm-wee
                command: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                    - .node_modules

    test:
        working_directory: ~/generator-angular-bro
        docker:
            - image: circleci/node:6.11.0
        steps:
            - run:
                name: unit-tests
                command: npm test -- --reporter mocha-junit-reporter --reporter-options mochaFile=junit.xml
            - run:
                name: collect-coverage
                command: npm run coverage -- --report-dir coverage/
            - run:
                name: report-coveralls-coverage
                command: npm run coveralls
            - store_artifacts:
                path: junit.xml
                prefix: tests
            - store_artifacts:
                path: coverage
                prefix: coverage

    deploy:
        working_directory: ~/generator-angular-bro
        docker:
            - image: circleci/node:6.11.0
        steps:
            - run:
                name: prep-node-credentials
                command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            - run:
                name: publish-npm
                command: npm publish

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - test:
                requires:
                    - build
            - deploy:
                requires:
                    - build
                    - test
                filters:
                    branches:
                        only: master
